### ISSUE TITLE
Custom sprites not working

### ISSUE THREAD

**Issue by GDReimu** [crewly/comboBurst#12]
I've done everything the tutorial said to do and each time I try to open a level with the custom sprites, the game crashes entirely. Could I get a video tutorial on how to do it properly or some info on how to get it to work?

**Comment by crewly** [comment]
I'll upload a video next week on how to create custom sprites. I should also make the sprites not load instead of crashing the game entirely

**Comment by crewly** [comment]
Here's the long awaited video: https://youtu.be/Wx0gls0S7ss
