### ISSUE TITLE
Level not loading is still an issue.

### ISSUE THREAD

**Issue by mesmerneru** [crewly/comboBurst#6]
Hey there, I found out there's a Geode 3.0.0 Beta 5, so I downloaded it, and I updated Combo Burst. After doing so, I tried to play a level with Combo Burst on and the level did not load yet again. This is Combo Burst V1.1.0 Beta-3 and I've been using Combo Burst since 2.204. Hopefully there's a fix for this soon!

**Comment by crewly** [comment]
@Fans-And-Eggy Combo Burst v1.1.0-beta.5 was released yesterday for beta.5 and is on the index. You may also download it [here](https://github.com/crewly/comboBurst/releases/tag/v1.1.0-beta.5)

**Comment by mesmerneru** [comment]
Thank you, I will try this and I will let you know if I run into this issue again.

**Comment by mesmerneru** [comment]
It works now, thank you Crewly.
